spring.application.name=Alura_Series

#locacalhost pq estï¿½ em ambiente local, gerenciador-pedidos ï¿½ o nome do banco
spring.datasource.url=jdbc:postgresql://localhost/alura_series
#nomeusuï¿½rio
spring.datasource.username=postgres
#senha
spring.datasource.password=123456
#driver do banco
spring.datasource.driver-class-name=org.postgresql.Driver
#dialeto
hibernate.dialect=org.hibernate.dialect.HSQLDialect

#informar que se tiver alterecao nas classes, atualizar no banco
spring.jpa.hibernate.ddl-auto=update

#para ver as operações realizadas no banco
spring.jpa.show-sql=true
spring.jpa.format-sql=true
