spring.application.name=Grupo-pedidos

#locacalhost pq est� em ambiente local, gerenciador-pedidos � o nome do banco
spring.datasource.url=jdbc:postgresql://localhost/gerenciador-pedidos
#nomeusu�rio
spring.datasource.username=postgres
#senha
spring.datasource.password=123456
#driver do banco
spring.datasource.driver-class-name=org.postgresql.Driver
#dialeto
hibernate.dialect=org.hibernate.dialect.HSQLDialect

#informar que se tiver altere��o nas classes, atualizar no banco
spring.jpa.hibernate.ddl-auto=update
