#locacalhost pq está em ambiente local, alura_series é o nome do banco
spring.datasource.url=jdbc:postgresql://${DB_HOST}/${DB_NAME}
#nomeusuário
spring.datasource.username=${DB_USER}
#senha
spring.datasource.password=${DB_PASSWORD}
#driver do banco
spring.datasource.driver-class-name=org.postgresql.Driver
#dialeto
hibernate.dialect=org.hibernate.dialect.HSQLDialect

#informar que se tiver altereção nas classes, atualizar no banco
spring.jpa.hibernate.ddl-auto=update
